use_frameworks!

platform :ios, '11.1'

target 'OpenCV-Dynamic-Framework_Example' do
  pod 'OpenCV-Dynamic-Framework', :path => '../'

  target 'OpenCV-Dynamic-Framework_Tests' do
    inherit! :search_paths

    
  end
end
